### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by mellbratt** [Cinezaster/SDS011#1]
Hello!

I have a hard time getting this to work - does it work for you? Would you care to help out with some troubleshooting?

Cheers,
Anders

**Comment by Cinezaster** [comment]
Hi @mellbratt ,

I did and does work for me. 
Did you try the example sketch. Can you share your code?
I don't have a particle on hand, so I cannot test any code at the moment, although I have a particle running with the SDS011 in a project.

**Comment by mellbratt** [comment]
Swapped out all my hardware and now it's working! Sorry for bothering you! Will go back and pick apart and try to figure out what is wrong with my previous one...
