### ISSUE TITLE
Not triggering unless manual trigger

### ISSUE THREAD

**Issue by m1kr0b1** [Cinezaster/SDS011#2]
Hey there!

I tried your library and the basic example in the usage.uno file, but I have an issue that perhaps you can help resolve.

When I plug this in for the first time it works, reports values, and then goes in sleep mode, PM sensor fan stops spinning. Aaaand that's it.
Unless I unplug the 5v pin, plug it back in, works again, and goes back to sleep.

I have it plugged in as:
RX to TX, TX to RX, GND to GND, 5V to VIN.

Anything else I should be doing?

**Comment by m1kr0b1** [comment]
Yeah, ignore that, all is good. Started working all of a sudden.

**Comment by Cinezaster** [comment]
Hi @m1kr0b1 good luck with it going to close this issue
